### ISSUE TITLE
在执行最后一步运行docker-compose时编码错误

### ISSUE THREAD

**Issue by A3475** [QingdaoU/OnlineJudgeDeploy#1]
以下是错误报告
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 68, in main
    command()
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 115, in perform_command
    project = project_from_options('.', options)
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/command.py", line 37, in project_from_options
    override_dir=options.get('--project-directory'),
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/command.py", line 91, in get_project
    config_data = config.load(config_details)
  File "/usr/local/lib/python2.7/dist-packages/compose/config/config.py", line 383, in load
    service_dicts = load_services(config_details, main_file)
  File "/usr/local/lib/python2.7/dist-packages/compose/config/config.py", line 481, in load_services
    return build_services(service_config)
  File "/usr/local/lib/python2.7/dist-packages/compose/config/config.py", line 460, in build_services
    for name, service_dict in service_config.items()
  File "/usr/local/lib/python2.7/dist-packages/compose/config/config.py", line 445, in build_service
    service_dict = process_service(resolver.run())
  File "/usr/local/lib/python2.7/dist-packages/compose/config/config.py", line 712, in process_service
    service_dict['volumes'] = resolve_volume_paths(working_dir, service_dict)
  File "/usr/local/lib/python2.7/dist-packages/compose/config/config.py", line 1080, in resolve_volume_paths
    for volume in service_dict['volumes']
  File "/usr/local/lib/python2.7/dist-packages/compose/config/config.py", line 1094, in resolve_volume_path
    container_path, host_path = split_path_mapping(volume)
  File "/usr/local/lib/python2.7/dist-packages/compose/config/config.py", line 1180, in split_path_mapping
    if ':' in volume_config:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 11: ordinal not in range(128)

**Comment by virusdefender** [comment]
你修改过这个文件么？

**Comment by A3475** [comment]
没有，是在Ubuntu中文环境下打开的，和Ubuntu语言有关系?

**Comment by A3475** [comment]
已测试，无关

**Comment by A3475** [comment]
已查明，python2的锅，用python3运行无报错
