### ISSUE TITLE
证书问题

### ISSUE THREAD

**Issue by oneofsunshine** [QingdaoU/OnlineJudgeDeploy#10]
因证书问题导致oj-backend异常退出，logs: `<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)> (url: https://sentry.io/api/263057/store/)`，是因为使用py3.6要ssl认证导致的吗？mac ox可以通过使用亚马逊的证书解决此问题吗？

**Comment by virusdefender** [comment]
求贴一些完整的日志，这句话看不出来是哪里出现了问题。

**Comment by oneofsunshine** [comment]
```
2018-03-05 12:11:15,351 CRIT Supervisor running as root (no user in config file)
2018-03-05 12:11:15,371 INFO RPC interface 'supervisor' initialized
2018-03-05 12:11:15,371 CRIT Server 'inet_http_server' running without any HTTP authentication checking
2018-03-05 12:11:15,372 INFO supervisord started with pid 7
2018-03-05 12:11:15,863 INFO spawned: 'celery' with pid 78
2018-03-05 12:11:15,870 INFO spawned: 'nginx' with pid 79
2018-03-05 12:11:15,881 INFO spawned: 'gunicorn' with pid 80
2018-03-05 12:11:21,025 INFO success: celery entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2018-03-05 12:11:21,027 INFO success: nginx entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2018-03-05 12:11:21,028 INFO success: gunicorn entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
Django VERSION (1, 11, 4, 'final', 0)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 189, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused
	Is the server running on host "oj-postgres" (172.18.0.2) and accepting
	TCP/IP connections on port 5432?


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 83, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 20, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/loader.py", line 52, in __init__
    self.build_graph()
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/loader.py", line 209, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 65, in applied_migrations
    self.ensure_schema()
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 52, in ensure_schema
    if self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor()):
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 254, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 229, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 189, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: could not connect to server: Connection refused
	Is the server running on host "oj-postgres" (172.18.0.2) and accepting
	TCP/IP connections on port 5432?

[2018-03-08 12:33:05] - [ERROR] - [sentry.errors:678]  - Sentry responded with an error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)> (url: https://sentry.io/api/263057/store/)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/local/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/raven/utils/http.py", line 38, in connect
    sock, ca_certs=ca_certs, cert_reqs=ssl.CERT_REQUIRED)
  File "/usr/local/lib/python3.6/ssl.py", line 1149, in wrap_socket
    ciphers=ciphers)
  File "/usr/local/lib/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/usr/local/lib/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/local/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/raven/transport/threaded.py", line 165, in send_sync
    super(ThreadedHTTPTransport, self).send(url, data, headers)
  File "/usr/local/lib/python3.6/site-packages/raven/transport/http.py", line 43, in send
    ca_certs=self.ca_certs,
  File "/usr/local/lib/python3.6/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/local/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.6/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/usr/local/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)>
b'Sentry responded with an error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)> (url: https://sentry.io/api/263057/store/)'
[2018-03-08 12:33:05] - [ERROR] - [sentry.errors.uncaught:700]  - ['OperationalError: could not connect to server: Connection refused\n\tIs the server running on host "oj-postgres" (172.18.0.2) and accepting\n\tTCP/IP connections on port 5432?\n', '  File "manage.py", line 12, in <module>', '  File "django/core/management/__init__.py", line 363, in execute_from_command_line', '  File "django/core/management/__init__.py", line 355, in execute', '  File "django/core/management/base.py", line 283, in run_from_argv', '  File "django/core/management/base.py", line 330, in execute', '  File "django/core/management/commands/migrate.py", line 83, in handle', '  File "django/db/migrations/executor.py", line 20, in __init__', '  File "django/db/migrations/loader.py", line 52, in __init__', '  File "django/db/migrations/loader.py", line 209, in build_graph', '  File "django/db/migrations/recorder.py", line 65, in applied_migrations', '  File "django/db/migrations/recorder.py", line 52, in ensure_schema', '  File "django/db/backends/base/base.py", line 254, in cursor', '  File "django/db/backends/base/base.py", line 229, in _cursor', '  File "django/db/backends/base/base.py", line 213, in ensure_connection', '  File "django/db/utils.py", line 94, in __exit__', '  File "django/utils/six.py", line 685, in reraise', '  File "django/db/backends/base/base.py", line 213, in ensure_connection', '  File "django/db/backends/base/base.py", line 189, in connect', '  File "django/db/backends/postgresql/base.py", line 176, in get_new_connection', '  File "psycopg2/__init__.py", line 130, in connect']
b'[\'OperationalError: could not connect to server: Connection refused\\n\\tIs the server running on host "oj-postgres" (172.18.0.2) and accepting\\n\\tTCP/IP connections on port 5432?\\n\', \'  File "manage.py", line 12, in <module>\', \'  File "django/core/management/__init__.py", line 363, in execute_from_command_line\', \'  File "django/core/management/__init__.py", line 355, in execute\', \'  File "django/core/management/base.py", line 283, in run_from_argv\', \'  File "django/core/management/base.py", line 330, in execute\', \'  File "django/core/management/commands/migrate.py", line 83, in handle\', \'  File "django/db/migrations/executor.py", line 20, in __init__\', \'  File "django/db/migrations/loader.py", line 52, in __init__\', \'  File "django/db/migrations/loader.py", line 209, in build_graph\', \'  File "django/db/migrations/recorder.py", line 65, in applied_migrations\', \'  File "django/db/migrations/recorder.py", line 52, in ensure_schema\', \'  File "django/db/backends/base/base.py", line 254, in cursor\', \'  File "django/db/backends/base/base.py", line 229, in _cursor\', \'  File "django/db/backends/base/base.py", line 213, in ensure_connection\', \'  File "django/db/utils.py", line 94, in __exit__\', \'  File "django/utils/six.py", line 685, in reraise\', \'  File "django/db/backends/base/base.py", line 213, in ensure_connection\', \'  File "django/db/backends/base/base.py", line 189, in connect\', \'  File "django/db/backends/postgresql/base.py", line 176, in get_new_connection\', \'  File "psycopg2/__init__.py", line 130, in connect\']'
Sentry is attempting to send 1 pending error messages
Waiting up to 10 seconds
Press Ctrl-C to quit
Failed to migrate, going to retry...
Django VERSION (1, 11, 4, 'final', 0)
Operations to perform:
  Apply all migrations: account, announcement, auth, conf, contenttypes, contest, options, problem, sessions, submission
Running migrations:
  No migrations to apply.
Django VERSION (1, 11, 4, 'final', 0)
User root exists, operation ignored
Django VERSION (1, 11, 4, 'final', 0)
```

**Comment by virusdefender** [comment]
这个错误可以忽略吧，是上报错误日志的时候的提示，看起来并不是导致容器退出的原因

**Comment by oneofsunshine** [comment]
不好意思，才回复。我那天让李大佬帮忙看了一下，他说是可能是因为docker for mac的问题。我换了一台linux服务器。等再出问题我再来问～
非常感谢！
