### ISSUE TITLE
启动服务报 TypeError

### ISSUE THREAD

**Issue by 2571464841** [QingdaoU/OnlineJudgeDeploy#113]
我在CentOS上安装了依赖以及docker，拉取完成项目后，
使用以下命令启动服务
`docker-compose up -d`
然后报类型错误
![Uploading 00000.jpg…]()

**Comment by 2571464841** [comment]
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.9.16/bin/docker-compose", line 8, in <module>
    sys.exit(main())
  File "/root/.pyenv/versions/3.9.16/lib/python3.9/site-packages/compose/cli/main.py", line 81, in main
    command_func()
  File "/root/.pyenv/versions/3.9.16/lib/python3.9/site-packages/compose/cli/main.py", line 200, in perform_command
    project = project_from_options('.', options)
  File "/root/.pyenv/versions/3.9.16/lib/python3.9/site-packages/compose/cli/command.py", line 60, in project_from_options
    return get_project(
  File "/root/.pyenv/versions/3.9.16/lib/python3.9/site-packages/compose/cli/command.py", line 152, in get_project
    client = get_client(
  File "/root/.pyenv/versions/3.9.16/lib/python3.9/site-packages/compose/cli/docker_client.py", line 41, in get_client
    client = docker_client(
  File "/root/.pyenv/versions/3.9.16/lib/python3.9/site-packages/compose/cli/docker_client.py", line 124, in docker_client
    kwargs = kwargs_from_env(environment=environment, ssl_version=tls_version)
TypeError: kwargs_from_env() got an unexpected keyword argument 'ssl_version'

**Comment by FengZhe-ZYH** [comment]
你好，我在进行部署时也遇到了这个问题，我的解决方式如下：

首先，我尝试将docker降级为6.1.3，这解决了**ssl_version**的问题
```conda
pip install docker==6.1.3
```
但是又会有如下报错：
```
urllib3.exceptions.URLSchemeUnknown: Not supported URL scheme http+docker
```
我尝试将requests降级为2.31.0
```conda
pip install requests==2.31.0
```
之后就能成功完成部署了，但是还未投入使用，后续可能存在别的问题，希望这些能够帮到大家。
