### ISSUE TITLE
如何重新构建

### ISSUE THREAD

**Issue by evrmji** [QingdaoU/OnlineJudgeDeploy#4]
judge server 无法正常运行

**Comment by virusdefender** [comment]
请详细说明错误原因和现象和日志

**Comment by evrmji** [comment]
Judge server:

```
2017-12-11 13:42:07,724 ERROR HTTPConnectionPool(host='oj-backend', port=8000): Max retries exceeded with url: /api/judge_server_heartbeat/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f507b2a2c10>: Failed to establish a new connection: [Errno 111] Connection refused',))
Traceback (most recent call last):
  File "/code/service.py", line 20, in _request
    headers={"X-JUDGE-SERVER-TOKEN": token}, timeout=5).json()
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='oj-backend', port=8000): Max retries exceeded with url: /api/judge_server_heartbeat/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f507b2a2c10>: Failed to establish a new connection: [Errno 111] Connection refused',))
2017-12-11 13:42:07,726 ERROR HTTPConnectionPool(host='oj-backend', port=8000): Max retries exceeded with url: /api/judge_server_heartbeat/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f507b2a2c10>: Failed to establish a new connection: [Errno 111] Connection refused',))
Traceback (most recent call last):
  File "/code/service.py", line 37, in <module>
    service.heartbeat()
  File "/code/service.py", line 31, in heartbeat
    self._request(data)
  File "/code/service.py", line 23, in _request
    raise JudgeServiceError(e.message)
JudgeServiceError: HTTPConnectionPool(host='oj-backend', port=8000): Max retries exceeded with url: /api/judge_server_heartbeat/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f507b2a2c10>: Failed to establish a new connection: [Errno 111] Connection refused',))
2017-12-12 05:10:30,153 ERROR HTTPConnectionPool(host='oj-backend', port=8000): Max retries exceeded with url: /api/judge_server_heartbeat/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8898df9c10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
Traceback (most recent call last):
  File "/code/service.py", line 20, in _request
    headers={"X-JUDGE-SERVER-TOKEN": token}, timeout=5).json()
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='oj-backend', port=8000): Max retries exceeded with url: /api/judge_server_heartbeat/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8898df9c10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
2017-12-12 05:10:30,154 ERROR HTTPConnectionPool(host='oj-backend', port=8000): Max retries exceeded with url: /api/judge_server_heartbeat/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8898df9c10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
Traceback (most recent call last):
  File "/code/service.py", line 37, in <module>
    service.heartbeat()
  File "/code/service.py", line 31, in heartbeat
    self._request(data)
  File "/code/service.py", line 23, in _request
    raise JudgeServiceError(e.message)
JudgeServiceError: HTTPConnectionPool(host='oj-backend', port=8000): Max retries exceeded with url: /api/judge_server_heartbeat/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8898df9c10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
2017-12-12 05:10:55,543 ERROR HTTPConnectionPool(host='oj-backend', port=8000): Max retries exceeded with url: /api/judge_server_heartbeat/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f79ed945c10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
Traceback (most recent call last):
  File "/code/service.py", line 20, in _request
    headers={"X-JUDGE-SERVER-TOKEN": token}, timeout=5).json()
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='oj-backend', port=8000): Max retries exceeded with url: /api/judge_server_heartbeat/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f79ed945c10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
2017-12-12 05:10:55,545 ERROR HTTPConnectionPool(host='oj-backend', port=8000): Max retries exceeded with url: /api/judge_server_heartbeat/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f79ed945c10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
Traceback (most recent call last):
  File "/code/service.py", line 37, in <module>
    service.heartbeat()
  File "/code/service.py", line 31, in heartbeat
    self._request(data)
  File "/code/service.py", line 23, in _request
    raise JudgeServiceError(e.message)
JudgeServiceError: HTTPConnectionPool(host='oj-backend', port=8000): Max retries exceeded with url: /api/judge_server_heartbeat/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f79ed945c10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
2017-12-12 05:11:20,910 ERROR HTTPConnectionPool(host='oj-backend', port=8000): Max retries exceeded with url: /api/judge_server_heartbeat/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5f47daac10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
Traceback (most recent call last):
  File "/code/service.py", line 20, in _request
    headers={"X-JUDGE-SERVER-TOKEN": token}, timeout=5).json()
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='oj-backend', port=8000): Max retries exceeded with url: /api/judge_server_heartbeat/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5f47daac10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
2017-12-12 05:11:20,912 ERROR HTTPConnectionPool(host='oj-backend', port=8000): Max retries exceeded with url: /api/judge_server_heartbeat/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5f47daac10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
Traceback (most recent call last):
  File "/code/service.py", line 37, in <module>
    service.heartbeat()
  File "/code/service.py", line 31, in heartbeat
    self._request(data)
  File "/code/service.py", line 23, in _request
    raise JudgeServiceError(e.message)
JudgeServiceError: HTTPConnectionPool(host='oj-backend', port=8000): Max retries exceeded with url: /api/judge_server_heartbeat/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5f47daac10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
2017-12-12 05:11:46,333 ERROR HTTPConnectionPool(host='oj-backend', port=8000): Max retries exceeded with url: /api/judge_server_heartbeat/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f31421ebc10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
Traceback (most recent call last):
  File "/code/service.py", line 20, in _request
    headers={"X-JUDGE-SERVER-TOKEN": token}, timeout=5).json()
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='oj-backend', port=8000): Max retries exceeded with url: /api/judge_server_heartbeat/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f31421ebc10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
2017-12-12 05:11:46,334 ERROR HTTPConnectionPool(host='oj-backend', port=8000): Max retries exceeded with url: /api/judge_server_heartbeat/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f31421ebc10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
Traceback (most recent call last):
  File "/code/service.py", line 37, in <module>
    service.heartbeat()
  File "/code/service.py", line 31, in heartbeat
    self._request(data)
  File "/code/service.py", line 23, in _request
    raise JudgeServiceError(e.message)
JudgeServiceError: HTTPConnectionPool(host='oj-backend', port=8000): Max retries exceeded with url: /api/judge_server_heartbeat/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f31421ebc10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
2017-12-12 05:12:11,832 ERROR HTTPConnectionPool(host='oj-backend', port=8000): Max retries exceeded with url: /api/judge_server_heartbeat/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0accfa5c10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
Traceback (most recent call last):
  File "/code/service.py", line 20, in _request
    headers={"X-JUDGE-SERVER-TOKEN": token}, timeout=5).json()
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='oj-backend', port=8000): Max retries exceeded with url: /api/judge_server_heartbeat/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0accfa5c10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
2017-12-12 05:12:11,834 ERROR HTTPConnectionPool(host='oj-backend', port=8000): Max retries exceeded with url: /api/judge_server_heartbeat/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0accfa5c10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
Traceback (most recent call last):
  File "/code/service.py", line 37, in <module>
    service.heartbeat()
  File "/code/service.py", line 31, in heartbeat
    self._request(data)
  File "/code/service.py", line 23, in _request
    raise JudgeServiceError(e.message)
JudgeServiceError: HTTPConnectionPool(host='oj-backend', port=8000): Max retries exceeded with url: /api/judge_server_heartbeat/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0accfa5c10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))

```
log:
```
[2017-12-11 13:42:03 +0000] [5] [INFO] Starting gunicorn 19.7.1
[2017-12-11 13:42:03 +0000] [5] [INFO] Listening at: http://0.0.0.0:8080 (5)
[2017-12-11 13:42:03 +0000] [5] [INFO] Using worker: threads
[2017-12-11 13:42:03 +0000] [13] [INFO] Booting worker with pid: 13
[2017-12-11 13:42:03 +0000] [16] [INFO] Booting worker with pid: 16
```

**Comment by virusdefender** [comment]
请认真看文档，看下 backend_url 是做什么的

**Comment by yanyige** [comment]
请问你们最后解决了吗？同样的问题
